#!/usr/bin/env php
<?php

use PhpSchool\CliMenu\CliMenu;
use PhpSchool\CliMenu\CliMenuBuilder;

$rootOfApp = realpath(__DIR__ . "/../../../");

require_once($rootOfApp . "/bootstrap.php");
ini_set("memory_limit", "256M");

$scope = APP_CORE_NAME;

/** @var \Segura\AppCore\Services\EnvironmentService $environment */
$environment = $scope::Container()->get(\Segura\AppCore\Services\EnvironmentService::class);

/** @var \Segura\AppCore\DbConfig|null $databaseConfigs */
try {
    $databaseConfigs = $scope::Container()->get(\Segura\AppCore\DbConfig::class);
}catch(\Segura\AppCore\Exceptions\DbConfigException $dbConfigException){
    $databaseConfigs = null;
}

if($environment->isSet('MYSQL_HOST')) {
    $scope::waitForMySQLToBeReady();
}
$sdkOutputPath = APP_ROOT . "/vendor/segura/lib" . strtolower(APP_NAME);

if(class_exists("\Zenderator\Zenderator")) {
    $zenderator = new \Zenderator\Zenderator(
        $rootOfApp,
        $databaseConfigs
    );
}else{
    $zenderator = null;
}

$automize = new \Zenderator\Automize\Automize(
    $zenderator,
    $sdkOutputPath
);
$automize->run();